### ISSUE TITLE
[Feature request] Safetensors?

### ISSUE THREAD

**Issue by R4rum** [bbc-mc/sdweb-merge-block-weighted-gui#12]
I am able to merge models in the safetensor format, but it's at least not in the UI that they could be saved in that format. Could you add support? I'm not sure why it's not the default in A1111, really.

**Comment by Verszy** [comment]
I'd like this too, but as a stopgap we can take an MBW output and merge it with itself at an alpha of 0 to convert it from within the webUI. It's a little on the convoluted side, but it works.

**Comment by bbc-mc** [comment]
Hi, I add support for safetensors.
Enjoy!
