### ISSUE TITLE
[enhancement] Allow multi-merge or queue merges

### ISSUE THREAD

**Issue by hassan-sd** [bbc-mc/sdweb-merge-block-weighted-gui#5]
Thanks for the awesome extension. 

One feature request is to queue up multiple merges. One example being:

- As a user, I can choose "Merge all" to merge Model A and Model B across all preset templates
  In this example, I could run a merge for my models across all the variation templates I have listed, this is quick way for me to just analyze the best merges out of the templates I have 
  
  
- As a user, I can add merge settings to a queue, starting the queue when I have my list ready.
  In this example it allows me to focus on the variations I want to test out in planning, then execute them all in a queued sequence.
  
 
 **Mockups**
 
 
![image](https://user-images.githubusercontent.com/119671806/209401262-470c4b6b-581b-4641-9f34-bb9b38f92adc.png)

**Comment by bbc-mc** [comment]
Thank you for request.

I'v already working on it with a bit different idea.
anyway, multi-merge will come soon.
