### ISSUE TITLE
[suggestion] Short note about the ratio in merging section

### ISSUE THREAD

**Issue by alansmithee-johndoe** [bbc-mc/sdweb-merge-block-weighted-gui#7]
Thanks for your great job! I'm enjoying it.

Then, I'm little confused about the ratio in merging section in MBW tab. 
So, how about showing short note about the ratio in merging section.

I guess the ratio of each block is for ModelB.

**Comment by bbc-mc** [comment]
Thank you for pointing this out, and I'm happy to hear you enjoying it !!

The meaning of the ratio values in the MBW window has been taken over from "Checkpoint Merger" and is also said to be "a bit confusing". (Yes, ratio value is for Model B, as `(1-M)*A + M*B` )
* As a side note, I also created an Extension that visualizes it, HAHA.

As when Im creating it, I thought there are already many users of the WebUI, and they should know and used to be with the values and the meaning.

Btw, talking about additional message on UI, Its a bit hard to do so.
UI position is strongly controled by Gradio UI Library, and Text need big blank space on it. Which break ballance of UI. 
I want UI keep simple/small and stay Upper-Left side, mainly for useablity.
MBW has big UI, and now already have over-sized for my opinion.

I will take it consideration If I found some way to do.

**Comment by alansmithee-johndoe** [comment]
>ratio value is for Model B, as ```(1-M)*A + M*B```

Thanks a lot. Now I'm fully understood ;)

![001](https://user-images.githubusercontent.com/121098079/209814088-30cdcbb0-ae20-454f-ba08-580113a7534a.png)

[Nice!](https://github.com/bbc-mc/merge-percentage-visualize)

>As when Im creating it, I thought there are already many users of the WebUI, and they should know and used to be with the values and the meaning.

That sounds difficult problem :(

>UI position is strongly controled by Gradio UI Library, Text need big blank space on it.

Wtf!

>MBW has big UI, and now already have over-sized for my opinion.

"Keep it short and simple." is important principle.

>I will take it consideration If I found some way to do.

I hope you'll get hit by a nice idea, I mean, good luck!
